spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://25.33.65.57:5433/internet_store
spring.datasource.username=postgres
spring.datasource.password=root
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
storage.location=./uploads